### ISSUE TITLE
Strange error message when refreshing page or changing scene.

### ISSUE THREAD

**Issue by zLaddeus** [BlitzKraig/fvtt-CommunityLighting#27]
Some of my players get this error when refreshing the page or changing scene.
I've used Find the Culprit to find that it is the CommintyLightning module that causes it.

![image](https://user-images.githubusercontent.com/71599968/103038276-59c90f00-456e-11eb-98c4-f514a0e68274.png)

![image](https://user-images.githubusercontent.com/71599968/103038374-95fc6f80-456e-11eb-85c7-3d23786180d2.png)

Dunno what causes it.
I've tried to remove and install the module, but doesn't change anything.

**Comment by zLaddeus** [comment]
I created a new world, new actor and new NPC.
Only enabled the module, and get the same error.

![image](https://user-images.githubusercontent.com/71599968/103160992-1247ba80-47dc-11eb-91de-38354580bed2.png)

Seems like there is some sort of Permission issue? 

I don't get an error if the player is sett to Assistant GM for example.

**Comment by Kelmey** [comment]
I have the same issue. I created a separate issue for it because I didn't see this one. I'll try to close my duplicate.

Here is what I wrote in my issue.

Foundry 0.7.9
CL version 0.3.1

If I make a token emit light and assign a light animation from this mod an error popup occurs every time a player loads the scene. The error doesn't happen if a GM loads the scene.

I was using the alternate torch, blurred torch, and star light animations. The tokens with the light sources were NPCs, not player tokens. I verified the error doesn't happen if I use no animation, or a default animation.

Here is the error from the console.

foundry.js:3780 Error: User Test Player lacks permission to update Tokens in parent gEd5ruT1uhzaE6oE
at Function._onUpdate (D:\Programs\Foundry\FoundryVTT\resources\app\dist\database\odm\embedded.js:1:7985)
at runNextTicks (internal/process/task_queues.js:59:5)
at processImmediate (internal/timers.js:412:9)
at process.topLevelDomainCallback (domain.js:130:23)
at async Socket.handleEvent (D:\Programs\Foundry\FoundryVTT\resources\app\dist\sockets.js:1:2262)
_handleError @ foundry.js:3780
foundry.js:11476 Uncaught (in promise) Error: User Test Player lacks permission to update Tokens in parent gEd5ruT1uhzaE6oE
at Function._onUpdate (D:\Programs\Foundry\FoundryVTT\resources\app\dist\database\odm\embedded.js:1:7985)
at runNextTicks (internal/process/task_queues.js:59:5)
at processImmediate (internal/timers.js:412:9)
at process.topLevelDomainCallback (domain.js:130:23)
at async Socket.handleEvent (D:\Programs\Foundry\FoundryVTT\resources\app\dist\sockets.js:1:2262)

**Comment by Dick-K** [comment]
I'm running Foundry 0.7.9 and Community Lighting 0.3.1 and am getting the same error on a couple of scenes, but not for all scenes or all players, although it is consistent for the scene/player combinations which it does affect.

I've run through all my modules, turning them off one by one. Goes away if I turn off Community Lighting.

**Comment by BlitzKraig** [comment]
Thanks for all the info everyone. As far as I can tell, this won't cause any actual problems, though it is annoying.

I'll be taking a look at this soon

**Comment by BlitzKraig** [comment]
I think this might be fixed in the latest updates.
Can anyone confirm?

Thanks

**Comment by Dick-K** [comment]
I've tested this on Foundry 0.8.7 and CL 0.4.6. It happened on a couple of maps the first time I ran through them, activating them one after the other, but I couldn't repeat this in the same session. I rebooted the server and relogged with the player, hasn't happened again. Something's been reset and appears to have done the job. I'll keep an eye on it, but looks to be solved, thanks a lot.

**Comment by BlitzKraig** [comment]
I've tracked down the reason for the error messages. I can see one place where it _might_ still appear in the latest versions, so I'll make sure to fix that too just in case.

If you do see the message, rest assured it will be fixed in the next update.

Thanks

**Comment by Kelmey** [comment]
Thanks much for looking into this!

**Comment by BlitzKraig** [comment]
Let me know if you see any more errors like that, they should all be resolved
