### ISSUE TITLE
Warning Message in the log whenever get in the game or load a scene

### ISSUE THREAD

**Issue by Vertigo522** [BlitzKraig/fvtt-CommunityLighting#29]
<img width="407" alt="Immagine" src="https://user-images.githubusercontent.com/60001721/106065173-30664a80-60fb-11eb-9180-d5630a3dd232.png">

I get a warning everytime i get into the game or load a scene (Even without lights), saying that the module cannot load content for a file that doesn't exist (pixi-filters.js.map).

I've noticed that this results in general slow downs and hiccups in server and game stability.

**Comment by BlitzKraig** [comment]
Hi,
This won't affect your client at all, the message is only generated when devtools is open.

A mapping file does not exist for that minified file, which is 100% fine and expected behaviour, pixi-filters is a dependency that I don't intend to edit or debug in any way.

If you are seeing problems, this is a red herring. Feel free to open an new issue describing the problems you see.
