### ISSUE TITLE
Use optgroup for grouping lighting entries

### ISSUE THREAD

**Issue by rmasoni** [BlitzKraig/fvtt-CommunityLighting#4]
I couldn't find where this was set up in the code, but the “Light Animation Type” `select` should use `optgroup` to group the options by author — it's the HTML standard and most appropriate element for this.

There's no nesting for `optgroup` though, so it's not possible to put everything inside a parent “Community Lighting” group. My suggestion is to use `Community Lighting (Author)`, like this:

<img width="325" alt="image" src="https://user-images.githubusercontent.com/62244/97068725-a3ae6c80-15a0-11eb-9cef-ae562cc1b317.png">

Instead of:

<img width="325" alt="image" src="https://user-images.githubusercontent.com/62244/97068909-19670800-15a2-11eb-9914-3fae9dabc613.png">

**Comment by BlitzKraig** [comment]
Hi,The animation selection is foundry core functionality. I do plan on doing something with it, the current solution is just a workaround.On 24 Oct 2020 06:42, Rafael Masoni <notifications@github.com> wrote:

I couldn't find where this was set up in the code, but the “Light Animation Type” select should use optgroup to group the options by author — it's the HTML standard and most appropriate element for this.

There's no nesting for optgroup though, so it's not possible to put everything inside a parent “Community Lighting” group. My suggestion is to use Community Lighting (Author), like this:



Instead of:

**Comment by BlitzKraig** [comment]
Hi rmasoni, I'm working on some features that manipulate the form for other reasons at the moment, so I think I'm going to try and add in the `optgroup` for next release too. Thanks for the suggestion!

**Comment by rmasoni** [comment]
Cool, thanks!
